export const OFFICE_ORDER_CREATE_REQUEST = 'OFFICE_ORDER_CREATE_REQUEST'
export const OFFICE_ORDER_CREATE_SUCCESS = 'OFFICE_ORDER_CREATE_SUCCESS'
export const OFFICE_ORDER_CREATE_FAIL = 'OFFICE_ORDER_CREATE_FAIL'
export const OFFICE_ORDER_CREATE_RESET = 'OFFICE_ORDER_CREATE_RESET'

export const OFFICE_ORDER_DETAILS_REQUEST = 'OFFICE_ORDER_DETAILS_REQUEST'
export const OFFICE_ORDER_DETAILS_SUCCESS = 'OFFICE_ORDER_DETAILS_SUCCESS'
export const OFFICE_ORDER_DETAILS_FAIL = 'OFFICE_ORDER_DETAILS_FAIL'

export const OFFICE_ORDER_LIST_MY_REQUEST = 'OFFICE_ORDER_LIST_MY_REQUEST'
export const OFFICE_ORDER_LIST_MY_SUCCESS = 'OFFICE_ORDER_LIST_MY_SUCCESS'
export const OFFICE_ORDER_LIST_MY_FAIL = 'OFFICE_ORDER_LIST_MY_FAIL'
export const OFFICE_ORDER_LIST_MY_RESET = 'OFFICE_ORDER_LIST_MY_RESET'