export const OFFICE_PRODUCT_LIST_REQUEST = 'OFFICE_PRODUCT_LIST_REQUEST'
export const OFFICE_PRODUCT_LIST_SUCCESS = 'OFFICE_PRODUCT_LIST_SUCCESS'
export const OFFICE_PRODUCT_LIST_FAIL = 'OFFICE_PRODUCT_LIST_FAIL'

export const OFFICE_PRODUCT_DETAILS_REQUEST = 'OFFICE_PRODUCT_DETAILS_REQUEST'
export const OFFICE_PRODUCT_DETAILS_SUCCESS = 'OFFICE_PRODUCT_DETAILS_SUCCESS'
export const OFFICE_PRODUCT_DETAILS_FAIL = 'OFFICE_PRODUCT_DETAILS_FAIL'

export const OFFICE_PRODUCT_DELETE_REQUEST = 'OFFICE_PRODUCT_DELETE_REQUEST'
export const OFFICE_PRODUCT_DELETE_SUCCESS = 'OFFICE_PRODUCT_DELETE_SUCCESS'
export const OFFICE_PRODUCT_DELETE_FAIL = 'OFFICE_PRODUCT_DELETE_FAIL'

export const OFFICE_PRODUCT_CREATE_REQUEST = 'OFFICE_PRODUCT_CREATE_REQUEST'
export const OFFICE_PRODUCT_CREATE_SUCCESS = 'OFFICE_PRODUCT_CREATE_SUCCESS'
export const OFFICE_PRODUCT_CREATE_FAIL = 'OFFICE_PRODUCT_CREATE_FAIL'
export const OFFICE_PRODUCT_CREATE_RESET = 'OFFICE_PRODUCT_CREATE_RESET'

export const OFFICE_PRODUCT_UPDATE_REQUEST = 'OFFICE_PRODUCT_UPDATE_REQUEST'
export const OFFICE_PRODUCT_UPDATE_SUCCESS = 'OFFICE_PRODUCT_UPDATE_SUCCESS'
export const OFFICE_PRODUCT_UPDATE_FAIL = 'OFFICE_PRODUCT_UPDATE_FAIL'
export const OFFICE_PRODUCT_UPDATE_RESET = 'OFFICE_PRODUCT_UPDATE_RESET'