# Generated by Django 4.0.5 on 2022-10-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_kitchenorder_kitchenproduct_kitchenorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenorderitem',
            old_name='order',
            new_name='kitchenOrder',
        ),
        migrations.RenameField(
            model_name='kitchenorderitem',
            old_name='product',
            new_name='kitchenProduct',
        ),
    ]
