# Generated by Django 4.0.5 on 2022-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_order_kitchenorderitem_kitchenorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenorderitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
