# Generated by Django 4.0.5 on 2022-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_kitchenorderitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenorderitem',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenproduct',
            name='countInStock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
