# Generated by Django 4.0.5 on 2022-10-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_customuser_is_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
