# Generated by Django 4.0.5 on 2022-10-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
