# Generated by Django 4.0.5 on 2022-10-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'employee'), (2, 'writer'), (3, 'supervisor'), (4, 'admin')], primary_key=True, serialize=False),
        ),
    ]
