# Generated by Django 4.0.5 on 2022-10-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_user_roles_alter_role_id_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
