# Generated by Django 4.0.5 on 2022-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='Designates whether the user is regular employee.', verbose_name='Employee status'),
        ),
    ]
